CREATE TABLE files
(
    file_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    filename VARCHAR(255)                            NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_files PRIMARY KEY (file_id),
    CONSTRAINT uc_files_filename UNIQUE (filename),
    CONSTRAINT FK_FILES_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id)
);